In [3]:
import numpy as np

import cv2

from dsec import DSEC

import time

In [4]:
dsec = DSEC()
events_h5 = dsec.get_event_file(dsec.seqs[0])


In [6]:
t = time.time()
events_direct = np.zeros(315285500)
events_h5["events"]["x"].read_direct(events_direct)
print(time.time() - t)

2.106527805328369


In [7]:
t = time.time()
events_direct = np.zeros(315285500)
np.array(events_h5["events"]["x"])
print(time.time() - t)

2.7129321098327637


In [12]:
t = time.time()
events_direct = np.zeros(315285500)
events_h5["events"]["x"].read_direct(events_direct)
e = events_direct[115285500:215285500]
print(e.shape)
print(time.time() - t)

(100000000,)
3.3557212352752686


In [14]:
t = time.time()
events_direct = np.zeros(315285500)
e = events_h5["events"]["x"][115285500:215285500]
print(e.shape)
print(time.time() - t)

(100000000,)
0.38013720512390137


In [28]:
res = (320, 240)
offset = (100, 50)
xs = np.arange(offset[0], res[0] + offset[0])
ys = np.arange(offset[1], res[1] + offset[1])

In [29]:
X, Y = np.meshgrid(xs, ys)
print(X)
print(Y)

[[100 101 102 ... 417 418 419]
 [100 101 102 ... 417 418 419]
 [100 101 102 ... 417 418 419]
 ...
 [100 101 102 ... 417 418 419]
 [100 101 102 ... 417 418 419]
 [100 101 102 ... 417 418 419]]
[[ 50  50  50 ...  50  50  50]
 [ 51  51  51 ...  51  51  51]
 [ 52  52  52 ...  52  52  52]
 ...
 [287 287 287 ... 287 287 287]
 [288 288 288 ... 288 288 288]
 [289 289 289 ... 289 289 289]]


In [27]:
coords = np.concatenate([X.reshape(-1, 1),
                         Y.reshape(-1, 1)], axis=1)
print(coords)

[[  0   0]
 [  1   0]
 [  2   0]
 ...
 [317 239]
 [318 239]
 [319 239]]
