In [1]:
import numpy as np

import cv2

from dsec import DSEC

from utils import dist2rect, rect2dist

In [ ]:
import time

In [2]:
dsec = DSEC()

In [15]:
rm = np.array(dsec.rectify_maps[0]['rectify_map'])

R = np.array(dsec.cams[0]['extrinsics']['R_rect0'])
dist = np.array(dsec.cams[0]['intrinsics']['cam0']['distortion_coeffs'])
k_dist = np.array(dsec.cams[0]['intrinsics']['cam0']['camera_matrix'])
k_rect = np.array(dsec.cams[0]['intrinsics']['camRect0']['camera_matrix'])
K_rect = np.array([[k_rect[0], 0, k_rect[2]],
                   [0, k_rect[1], k_rect[3]],
                   [0, 0, 1]])
K_dist = np.array([[k_dist[0], 0, k_dist[2]],
                   [0, k_dist[1], k_dist[3]],
                   [0, 0, 1]])

xys = np.array([[0, 0],
                [639, 0],
                [0, 479],
                [639, 479]])

In [25]:
xys_K = cv2.undistortPoints(xys.astype(np.float32), K_dist, dist).reshape(-1,2)
xys_K  = np.concatenate([xys_K, np.ones([len(xys_K), 1])], axis=1)

xys_rect = xys_K.dot(R.transpose())[:, :2] * k_rect[:2] + k_rect[2:4]
print(xys_rect)

[[-13.74142628  -4.9402896 ]
 [654.37295098  -4.84200129]
 [-12.39900617 491.82189056]
 [650.87186114 496.71564016]]


In [35]:
print(cv2.undistortPoints(xys.astype(np.float32), K_dist, dist).reshape(-1,2))

[[-0.61136687 -0.3839531 ]
 [ 0.53406453 -0.38732067]
 [-0.60644686  0.46766567]
 [ 0.530706    0.47254485]]


In [37]:
xys_rect = cv2.undistortPoints(xys.astype(np.float32), K_dist, dist).reshape(-1,2)
xys_rect = np.concatenate([xys_rect, np.ones([len(xys_rect), 1])], axis=1).dot(R.transpose())
print(xys_rect / xys_rect[:, [2]])
print(cv2.undistortPoints(xys.astype(np.float32), K_dist, dist, R=R).reshape(-1,2))

[[-0.59801326 -0.3852586   1.        ]
 [ 0.54736408 -0.38914693  1.        ]
 [-0.59505374  0.46160095  1.        ]
 [ 0.54066684  0.47484187  1.        ]]
[[-0.5980133  -0.3852586 ]
 [ 0.54736406 -0.38914692]
 [-0.59505373  0.46160096]
 [ 0.5406668   0.47484186]]


In [21]:
xys_rect = cv2.undistortPoints(xys.astype(np.float32), K_dist, dist, R=R).reshape(-1,2)
xys_rect = xys_rect * k_rect[:2] + k_rect[2:4]
print(xys_rect)

[[-11.99185877  -3.81315099]
 [656.1160433   -6.08125059]
 [-10.26552955 490.16689811]
 [652.20949029 497.89042471]]


In [20]:
xys_rect = cv2.undistortPoints(xys.astype(np.float32), K_dist, dist, R=R, P=K_rect).reshape(-1,2)
print(xys_rect)

[[-11.991862   -3.8131533]
 [656.116      -6.0812483]
 [-10.26552   490.1669   ]
 [652.2095    497.89044  ]]


In [4]:
print(rm[xys[:, 1], xys[:, 0]])

[[-11.992482   -3.8135486]
 [656.11633    -6.081475 ]
 [-10.26636   490.16754  ]
 [652.2097    497.89062  ]]


In [14]:
term_criteria = (cv2.TERM_CRITERIA_MAX_ITER | cv2.TERM_CRITERIA_EPS, 100, 0.001)
points = cv2.undistortPointsIter(xys.astype(np.float32), K_dist, dist, R, K_rect, criteria=term_criteria).reshape(-1, 2)
print(points)

[[-11.992482   -3.8135486]
 [656.11633    -6.081475 ]
 [-10.26636   490.16754  ]
 [652.2097    497.89062  ]]


In [24]:
print(rm)

<HDF5 dataset "rectify_map": shape (480, 640, 2), type "<f4">


In [ ]:
rm = np.array(dsec.rectify_maps[0]['rectify_map'])

R = np.array(dsec.cams[0]['extrinsics']['R_rect0'])
dist = np.array(dsec.cams[0]['intrinsics']['cam0']['distortion_coeffs'])
k_dist = np.array(dsec.cams[0]['intrinsics']['cam0']['camera_matrix'])
k_rect = np.array(dsec.cams[0]['intrinsics']['camRect0']['camera_matrix'])

K_dist = np.array([[k_dist[0], 0, k_dist[2]],
                   [0, k_dist[1], k_dist[3]],
                   [0, 0, 1]])

xys = np.array([[0, 0],
                [639, 0],
                [0, 479],
                [639, 479]])

xys_K = cv2.undistortPoints(xys.astype(np.float32), K_dist, dist).reshape(-1, 2)
xys_K_hom = np.concatenate([xys_K, np.ones([len(xys_K), 1]) ], axis=1)
xys_rect = xys_K_hom.dot(R.transpose())[:, :2] * k_rect[:2].reshape(1, 2) + k_rect[2:4].reshape(1, 2)
print(xys_rect)